### ISSUE TITLE
How to get F1 score @ IoU=0.1?

### ISSUE THREAD

**Issue by luyy12** [google-research-datasets/screen_annotation#3]
Hi, thank you for sharing the valuable datasets. I wonder how to calculate the F1 score @ IoU=0.1 since there are language dscriptions about the UI entity and they could not be exactly matched.

**Comment by gbaechler** [comment]
For the object detection tasks (like Screen Annotation), only the UI class and the bounding box information is used, the text description is discarded.

**Comment by luyy12** [comment]
> For the object detection tasks (like Screen Annotation), only the UI class and the bounding box information is used, the text description is discarded.
OK, got it. Thank you for your reply.
